# Generated by Django 6.0.5 on 2026-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='locked_for_audit',
            field=models.BooleanField(default=False),
        ),
    ]
