# Generated by Django 6.0.5 on 2026-05-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_emissionrecord_locked_for_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
